name: Screenshots

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #This job checks if the browserstack key exists. If it does not exist, do not attempt to take screenshots
  checksecret:
    name: check if BROWSERSTACK_KEY is set in github secrets
    runs-on: ubuntu-latest
    outputs:
      is_BROWSERSTACK_KEY_set: ${{ steps.checksecret_job.outputs.is_BROWSERSTACK_KEY_set }}
    steps:
      - name: Check whether unity activation requests should be done
        id: checksecret_step
        env:
            KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: |
            echo "is_BROWSERSTACK_KEY_set: ${{ env.KEY != '' }}"
            echo "::set-output name=is_BROWSERSTACK_KEY_set::${{ env.KEY != '' }}"

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    needs: checksecret
    if: needs.checksecret.outputs.is_BROWSERSTACK_KEY_set == true
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate Website Screenshots
      #Checks if the previous step ran. If it didn't skip this step as well
      if: ${{ success() }}
      run: |
         pip3 install --upgrade pip
         export BROWSERSTACK_KEY=${{secrets.BROWSERSTACK_KEY}}
         pip3 install selenium
         cd actions/screenshots && python3 screenshot.py
         
    - uses: actions/upload-artifact@v2
      #Checks if the previous step ran. If it didn't skip this step as well
      if: ${{ success() }}
      with:
        name: Screenshots
        path: actions/screenshots/*.png
