name: Screenshots

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check whether unity activation requests should be done
      id: checksecret
      env:
          KEY: ${{ secrets.BROWSERSTACK_KEY }}
      run: |
          echo "is_BROWSERSTACK_KEY_set: ${{ env.KEY != '' }}"
          echo "::set-output name=is_BROWSERSTACK_KEY_set::${{ env.KEY != '' }}"
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      if: ${{ steps.checksecret.outputs.is_BROWSERSTACK_KEY_set == 'true' }}

    - name: Generate Website Screenshots
      #Checks if the previous step ran. If it didn't skip this step as well
      if: ${{ steps.checksecret.outputs.is_BROWSERSTACK_KEY_set == 'true' }}
      run: |
         pip3 install --upgrade pip
         export BROWSERSTACK_KEY=${{secrets.BROWSERSTACK_KEY}}
         pip3 install selenium
         cd actions/screenshots && python3 screenshot.py
         
    - uses: actions/upload-artifact@v2
      #Checks if the previous step ran. If it didn't skip this step as well
      if: ${{ steps.checksecret.outputs.is_BROWSERSTACK_KEY_set == 'true' }}
      with:
        name: Screenshots
        path: actions/screenshots/*.png
